# Generated by Django 4.1.3 on 2022-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('main_video', models.FileField(upload_to='videos', verbose_name='کیفیت اصلی')),
                ('medium_quality_video', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='کیفیت متوسط')),
                ('low_quality_video', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='کیفیت پایین')),
                ('convert_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان تبدیل')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
